version: '3.8'

services:
  # Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: unloading_qc_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unloading_qc
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Web Application Next.js
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: unloading_qc_app
    restart: always
    ports:
      - "8010:3000"  # Akses Publik: 8010, Internal: 3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/unloading_qc?schema=public
      - AUTH_SECRET=b9ba598cedb990a0488e02eab0c9d9ad76dd03e8bd7cfdb5227c46a5d2aba3c0
      - AUTH_TRUST_HOST=true
    depends_on:
      - db

volumes:
  postgres_data:


